spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb?useSSL=false
    username: samyak
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

server:
  port: 8082
logging:
  file:
    name: paymentService.log
management:
  tracing:
    sampling:
      probability: 1.0

